# **Obtención y preparación de datos**

# OD22. Lectura y escritura de archivos con Pandas

## <font color='blue'>**Herramientas de Entrada/Salida (I/O)**</font>
Una característica crucial de Pandas es su capacidad para escribir y leer archivos de distintos formatos: Excel, CSV, HTML, JSON y muchos otros. Estos métodos nos permiten guardar los datos y las etiquetas de los objetos de Pandas en un archivo y cargarlos más tarde como instancias de Pandas Series o DataFrame. Para ello, Pandas nos entrega un conjunto de funciones de lectura (*readers*) de alto nivel a las que por ejemplo se puede acceder como `pandas.read_csv()`, las que generalmente devuelven un objeto pandas; y las funciones de escritura (*writers*) correspondientes son métodos a los que se puede acceder por ejemplo como `DataFrame.to_csv()`.

A continuación se muestra una tabla que contiene los *readers* y *writers* disponibles.


|   Tipo de Formato   | Descripción de la Data |    Reader    |  Writer |
| -------             | :-----                 |  :---------: | :-----: |
| text   |  CSV |  read_csv | to_csv |
| text |  Fixed-Width Text File| read_fwf |  |
| text   |  JSON | read_json | to_json |
| text   |  HTML |  read_html | to_html |
| text    |  Local clipboard|  read_clipboard | to_clipboard |
|    |  MS Excel |  read_excel | to_excel |
| binary   |  OpenDocument |  read_excel |  |
| binary |  HDF5 Format| read_hdf | to_hdf |
| binary   |  Feather Format | read_feather | to_feather |
| binary   |  Parquet Format |  read_parquet | to_parquet |
| binary    |  ORC Format|  read_orc | |
| binary   |  Msgpack |  read_msgpack | to_msgpack |
| binary |  Stata| read_stata | to_stata |
| binary   |  SAS | read_sas |  |
| binary   |  SPSS |  read_spss |  |
| binary    | Python Pickle Format|  read_pickle | to_pickle |
| SQL   |  SQL |  read_sql | to_sql |
| SQL    | Google BigQuery|  read_gbq | to_gbq |

El detalle de cada una de las funciones se encuentra en el siguiente <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html">link</a>.

## <font color='blue'>**Datos de trabajo**</font>

Para nuestro aprendizaje, utilizaremos la siguiente data, la cual contiene lo siguiente:
* __Pais__: Corresponde al nombre del país. Las etiquetas de fila para el conjunto de datos son los códigos de país de tres letras definidos en ISO 3166-1. La etiqueta de la columna para el conjunto de datos es _PAIS_.

* __Población__: La población se expresa en millones. La etiqueta de columna para el conjunto de datos es _POB_.

* __Área:__ El área se expresa en miles de kilómetros cuadrados. La etiqueta de la columna para el conjunto de datos es _AREA_.

* __Productom Interno Bruto__: El producto interno bruto se expresa en millones de dólares estadounidenses, según los datos de las Naciones Unidas para 2017.  La etiqueta de columna para el conjunto de datos es _PIB_.

* __Continente__: El continente es África, Asia, Oceanía, Europa, América. La etiqueta de columna para el conjunto de datos es _CONT_.

* __Independencia__: El día de la independencia es una fecha que conmemora la independencia de una nación. Las fechas se muestran en formato ISO 8601. Los primeros cuatro dígitos representan el año, los siguientes dos números son el mes y los dos últimos son para el día del mes. La etiqueta de la columna para el conjunto de datos es _IND_.

* __OCDE__: Si el país es miembro o no de la _OCDE_.

In [1]:
# Organizamos la data en un diccionario

data = {
    'CHN': {'PAIS': 'China', 'POB': 1_398.72, 'AREA': 9_596.96,
            'PGB': 12_234.78, 'CONT': 'Asia', 'OCDE': 'No'},
    'IND': {'PAIS': 'India', 'POB': 1_351.16, 'AREA': 3_287.26,
            'PGB': 2_575.67, 'CONT': 'Asia', 'IND': '1947-08-15', 'OCDE': 'No'},
    'USA': {'PAIS': 'US', 'POB': 329.74, 'AREA': 9_833.52,
            'PGB': 19_485.39, 'CONT': 'America','IND': '1776-07-04', 'OCDE': 'Si'},
    'IDN': {'PAIS': 'Indonesia', 'POB': 268.07, 'AREA': 1_910.93,
            'PGB': 1_015.54, 'CONT': 'Asia', 'IND': '1945-08-17', 'OCDE': 'No'},
    'BRA': {'PAIS': 'Brasil', 'POB': 210.32, 'AREA': 8_515.77,
            'PGB': 2_055.51, 'CONT': 'America', 'IND': '1822-09-07', 'OCDE': 'No'},
    'PAK': {'PAIS': 'Pakistan', 'POB': 205.71, 'AREA': 881.91,
            'PGB': 302.14, 'CONT': 'Asia', 'IND': '1947-08-14', 'OCDE': 'No'},
    'NGA': {'PAIS': 'Nigeria', 'POB': 200.96, 'AREA': 923.77,
            'PGB': 375.77, 'CONT': 'Africa', 'IND': '1960-10-01', 'OCDE': 'No'},
    'BGD': {'PAIS': 'Bangladesh', 'POB': 167.09, 'AREA': 147.57,
            'PGB': 245.63, 'CONT': 'Asia', 'IND': '1971-03-26', 'OCDE': 'No'},
    'RUS': {'PAIS': 'Rusia', 'POB': 146.79, 'AREA': 17_098.25,
            'PGB': 1_530.75, 'IND': '1992-06-12', 'OCDE': 'No'},
    'MEX': {'PAIS': 'Mexico', 'POB': 126.58, 'AREA': 1_964.38,
            'PGB': 1_158.23, 'CONT': 'America', 'IND': '1810-09-16', 'OCDE': 'Si'},
    'JPN': {'PAIS': 'Japon', 'POB': 126.22, 'AREA': 377.97,
            'PGB': 4_872.42, 'CONT': 'Asia', 'OCDE': 'Si'},
    'DEU': {'PAIS': 'Alemania', 'POB': 83.02, 'AREA': 357.11,
            'PGB': 3_693.20, 'CONT': 'Europe', 'OCDE': 'Si'},
    'FRA': {'PAIS': 'Francia', 'POB': 67.02, 'AREA': 640.68,
            'PGB': 2_582.49, 'CONT': 'Europe', 'IND': '1789-07-14', 'OCDE': 'Si'},
    'GBR': {'PAIS': 'UK', 'POB': 66.44, 'AREA': 242.50,
            'PGB': 2_631.23, 'CONT': 'Europe', 'OCDE': 'Si'},
    'ITA': {'PAIS': 'Italia', 'POB': 60.36, 'AREA': 301.34,
            'PGB': 1_943.84, 'CONT': 'Europe', 'OCDE': 'Si'},
    'ARG': {'PAIS': 'Argentina', 'POB': 44.94, 'AREA': 2_780.40,
            'PGB': 637.49, 'CONT': 'America', 'IND': '1816-07-09', 'OCDE': 'No'},
    'DZA': {'PAIS': 'Algeria', 'POB': 43.38, 'AREA': 2_381.74,
            'PGB': 167.56, 'CONT': 'Africa', 'IND': '1962-07-05', 'OCDE': 'No'},
    'CAN': {'PAIS': 'Canada', 'POB': 37.59, 'AREA': 9_984.67,
            'PGB': 1_647.12, 'CONT': 'America', 'IND': '1867-07-01', 'OCDE': 'Si'},
    'AUS': {'PAIS': 'Australia', 'POB': 25.47, 'AREA': 7_692.02,
            'PGB': 1_408.68, 'CONT': 'Oceania', 'OCDE': 'Si'},
    'CHL': {'PAIS': 'Chile', 'POB': 19.68, 'AREA': 756.10,
            'PGB': 317.6, 'CONT': 'America', 'IND': '1818-09-18', 'OCDE': 'Si'},
    'KAZ': {'PAIS': 'Kazakistan', 'POB': 18.53, 'AREA': 2_724.90,
            'PGB': 159.41, 'CONT': 'Asia', 'IND': '1991-12-16', 'OCDE': 'No'}

}

columns = ('PAIS', 'POB', 'AREA', 'PGB', 'CONT', 'IND')

Puede notar que faltan algunos de los datos. Por ejemplo, el continente de Rusia no se especifica porque se extiende por Europa y Asia. También faltan varios días de independencia porque la fuente de datos los omite.

In [2]:
import pandas as pd

Usaremos el constructor `pd.DataFrame` para crear la estructura en Pandas.

In [3]:
df = pd.DataFrame(data=data)
df

,CHN,IND,USA,IDN,BRA,PAK,NGA,BGD,RUS,MEX,...,DEU,FRA,GBR,ITA,ARG,DZA,CAN,AUS,CHL,KAZ
PAIS,China,India,US,Indonesia,Brasil,Pakistan,Nigeria,Bangladesh,Rusia,Mexico,...,Alemania,Francia,UK,Italia,Argentina,Algeria,Canada,Australia,Chile,Kazakistan
POB,1398.72,1351.16,329.74,268.07,210.32,205.71,200.96,167.09,146.79,126.58,...,83.02,67.02,66.44,60.36,44.94,43.38,37.59,25.47,19.68,18.53
AREA,9596.96,3287.26,9833.52,1910.93,8515.77,881.91,923.77,147.57,17098.25,1964.38,...,357.11,640.68,242.5,301.34,2780.4,2381.74,9984.67,7692.02,756.1,2724.9
PGB,12234.78,2575.67,19485.39,1015.54,2055.51,302.14,375.77,245.63,1530.75,1158.23,...,3693.2,2582.49,2631.23,1943.84,637.49,167.56,1647.12,1408.68,317.6,159.41
CONT,Asia,Asia,America,Asia,America,Asia,Africa,Asia,NaN,America,...,Europe,Europe,Europe,Europe,America,Africa,America,Oceania,America,Asia
OCDE,No,No,Si,No,No,No,No,No,No,Si,...,Si,Si,Si,Si,No,No,Si,Si,Si,No
IND,NaN,1947-08-15,1776-07-04,1945-08-17,1822-09-07,1947-08-14,1960-10-01,1971-03-26,1992-06-12,1810-09-16,...,NaN,1789-07-14,NaN,NaN,1816-07-09,1962-07-05,1867-07-01,NaN,1818-09-18,1991-12-16

Podemos transponer la estructura para que la data quede organizada con el *código_pais* como índice.

In [4]:
df = pd.DataFrame(data=data).T
df

           PAIS      POB      AREA       PGB     CONT OCDE         IND
CHN       China  1398.72   9596.96  12234.78     Asia   No         NaN
IND       India  1351.16   3287.26   2575.67     Asia   No  1947-08-15
USA          US   329.74   9833.52  19485.39  America   Si  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54     Asia   No  1945-08-17
BRA      Brasil   210.32   8515.77   2055.51  America   No  1822-09-07
PAK    Pakistan   205.71    881.91    302.14     Asia   No  1947-08-14
NGA     Nigeria   200.96    923.77    375.77   Africa   No  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63     Asia   No  1971-03-26
RUS       Rusia   146.79  17098.25   1530.75      NaN   No  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  America   Si  1810-09-16
JPN       Japon   126.22    377.97   4872.42     Asia   Si         NaN
DEU    Alemania    83.02    357.11    3693.2   Europe   Si         NaN
FRA     Francia    67.02    640.68   2582.49   Europe   Si  1789-07-14
GBR          UK    66.44     242.5   2631.23   Europe   Si         NaN
ITA      Italia    60.36    301.34   1943.84   Europe   Si         NaN
ARG   Argentina    44.94    2780.4    637.49  America   No  1816-07-09
DZA     Algeria    43.38   2381.74    167.56   Africa   No  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  America   Si  1867-07-01
AUS   Australia    25.47   7692.02   1408.68  Oceania   Si         NaN
CHL       Chile    19.68     756.1     317.6  America   Si  1818-09-18
KAZ  Kazakistan    18.53    2724.9    159.41     Asia   No  1991-12-16

Nuestra data está lista, veamos como escribir y leer archivos con pandas.

## <font color='blue'>**Uso de las funciones `read_csv()` y `.to_csv()` de Pandas**</font>

Un archivo **CSV** (_comma-separated values_), es un archivo de texto sin formato con una extensión .csv que contiene datos tabulares. Este es uno de los formatos de archivo más Populares para almacenar grandes cantidades de datos. Cada fila del archivo CSV representa una única fila de la tabla. Los valores en la misma fila están separados por comas de forma predeterminada, pero puede cambiar el separador a punto y coma, tabulación, espacio o algún otro carácter.

### __Escribir un archivo CSV__
Puede guardar su Pandas DataFrame como un archivo CSV con el método `.to_csv()`:

In [5]:
df.to_csv('data.csv')

¡Eso es todo! Ha creado el archivo `data.csv` en su directorio de trabajo actual. Ejecute el siguiente comando de consola para ver cómo se ve su archivo CSV:

In [6]:
!cat data.csv

,PAIS,POB,AREA,PGB,CONT,OCDE,IND
CHN,China,1398.72,9596.96,12234.78,Asia,No,
IND,India,1351.16,3287.26,2575.67,Asia,No,1947-08-15
USA,US,329.74,9833.52,19485.39,America,Si,1776-07-04
IDN,Indonesia,268.07,1910.93,1015.54,Asia,No,1945-08-17
BRA,Brasil,210.32,8515.77,2055.51,America,No,1822-09-07
PAK,Pakistan,205.71,881.91,302.14,Asia,No,1947-08-14
NGA,Nigeria,200.96,923.77,375.77,Africa,No,1960-10-01
BGD,Bangladesh,167.09,147.57,245.63,Asia,No,1971-03-26
RUS,Rusia,146.79,17098.25,1530.75,,No,1992-06-12
MEX,Mexico,126.58,1964.38,1158.23,America,Si,1810-09-16
JPN,Japon,126.22,377.97,4872.42,Asia,Si,
DEU,Alemania,83.02,357.11,3693.2,Europe,Si,
FRA,Francia,67.02,640.68,2582.49,Europe,Si,1789-07-14
GBR,UK,66.44,242.5,2631.23,Europe,Si,
ITA,Italia,60.36,301.34,1943.84,Europe,Si,
ARG,Argentina,44.94,2780.4,637.49,America,No,1816-07-09
DZA,Algeria,43.38,2381.74,167.56,Africa,No,1962-07-05
CAN,Canada,37.59,9984.67,1647.12,America,Si,1867-07-01
AUS,Australia,25.47,7692.02,1408.68,Oceania,Si,
CHL,Chile,19.68,756.1,317.6,America,Si,1818-09-18
KAZ,Kazakistan,18.53,2724.9,159.41,Asia,No,1991-12-16

Este archivo de texto contiene los datos separados por comas. La primera columna contiene las etiquetas de las filas. En algunos casos, los encontrará irrelevantes. Si no desea conservarlos, puede pasar el argumento `index=False` a `.to_csv()`.

### __Leer un archivo CSV__
Una vez que sus datos se guardan en un archivo CSV, es probable que desee cargarlos y usarlos. Puedes hacerlo con la función pandas `read_csv()`:

In [7]:
df = pd.read_csv('data.csv', index_col=0)
df

           PAIS      POB      AREA       PGB     CONT OCDE         IND
CHN       China  1398.72   9596.96  12234.78     Asia   No         NaN
IND       India  1351.16   3287.26   2575.67     Asia   No  1947-08-15
USA          US   329.74   9833.52  19485.39  America   Si  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54     Asia   No  1945-08-17
BRA      Brasil   210.32   8515.77   2055.51  America   No  1822-09-07
PAK    Pakistan   205.71    881.91    302.14     Asia   No  1947-08-14
NGA     Nigeria   200.96    923.77    375.77   Africa   No  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63     Asia   No  1971-03-26
RUS       Rusia   146.79  17098.25   1530.75      NaN   No  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  America   Si  1810-09-16
JPN       Japon   126.22    377.97   4872.42     Asia   Si         NaN
DEU    Alemania    83.02    357.11   3693.20   Europe   Si         NaN
FRA     Francia    67.02    640.68   2582.49   Europe   Si  1789-07-14
GBR          UK    66.44    242.50   2631.23   Europe   Si         NaN
ITA      Italia    60.36    301.34   1943.84   Europe   Si         NaN
ARG   Argentina    44.94   2780.40    637.49  America   No  1816-07-09
DZA     Algeria    43.38   2381.74    167.56   Africa   No  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  America   Si  1867-07-01
AUS   Australia    25.47   7692.02   1408.68  Oceania   Si         NaN
CHL       Chile    19.68    756.10    317.60  America   Si  1818-09-18
KAZ  Kazakistan    18.53   2724.90    159.41     Asia   No  1991-12-16

En este caso, la función `read_csv()` de Pandas devuelve un nuevo DataFrame con los datos y las etiquetas del archivo `data.csv`, que especificó con el primer argumento. Esta cadena puede ser cualquier ruta válida, incluidas las URL.

El parámetro `index_col` especifica la columna del archivo CSV que contiene las etiquetas de fila. Asigne un índice de columna de base cero a este parámetro. Debe determinar el valor de `index_col` cuando el archivo CSV contiene las etiquetas de fila para evitar cargarlas como datos.

In [8]:
# Si no incluímos index_col, los índices se convierten en una columna
df2 = pd.read_csv('data.csv')
df2.head()

  Unnamed: 0       PAIS      POB     AREA       PGB     CONT OCDE         IND
0        CHN      China  1398.72  9596.96  12234.78     Asia   No         NaN
1        IND      India  1351.16  3287.26   2575.67     Asia   No  1947-08-15
2        USA         US   329.74  9833.52  19485.39  America   Si  1776-07-04
3        IDN  Indonesia   268.07  1910.93   1015.54     Asia   No  1945-08-17
4        BRA     Brasil   210.32  8515.77   2055.51  America   No  1822-09-07

## <font color='blue'>**Usando Pandas para escribir y leer archivos Excel**</font>

Microsoft Excel es probablemente el software de hoja de cálculo más utilizado. Mientras que las versiones anteriores usaban archivos .xls binarios, Excel 2007 introdujo el nuevo archivo .xlsx basado en XML. Puede leer y escribir archivos de Excel en Pandas, de forma similar a los archivos CSV.

En el entorno que crea Colab vienen incluídas todas las librerías necesarias para leer y escribir desde Pandas a Excel. Si no las tuvieras iunstaladas deber´ñas hacerlo con:

```python
$ pip install xlwt openpyxl xlsxwriter xlrd
````
o utilizando Conda
```python
$ conda install xlwt openpyxl xlsxwriter xlrd
```
### __Escribir a un archivo Excel__
Utilizamos el método `.to_excel()`.

In [9]:
df.to_excel('data.xlsx')

El argumento 'data.xlsx' representa el archivo de destino y, opcionalmente, su ruta. La declaración anterior debería crear el archivo 'data.xlsx' en su directorio de trabajo actual. Veamos que si se creó el archivo:

In [10]:
! ls -la data*

-rw-r--r-- 1 root root 1099 Nov  4 18:57 data.csv
-rw-r--r-- 1 root root 6268 Nov  4 18:57 data.xlsx

### __Leer a un archivo Excel__
Utilizamos el método `read_excel()`.

`read_excel()` devuelve un nuevo DataFrame que contiene los valores de `data.xlsx`. También puede usar `read_excel()` con hojas de cálculo de OpenDocument o archivos .ods.

Nuevamente usaremos el parámetro `index_col` para evitar que la primera columna del Excel se convierta en una columna de datos y no en el índice.

In [11]:
df = pd.read_excel('data.xlsx', index_col=0)
df

           PAIS      POB      AREA       PGB     CONT OCDE         IND
CHN       China  1398.72   9596.96  12234.78     Asia   No         NaN
IND       India  1351.16   3287.26   2575.67     Asia   No  1947-08-15
USA          US   329.74   9833.52  19485.39  America   Si  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54     Asia   No  1945-08-17
BRA      Brasil   210.32   8515.77   2055.51  America   No  1822-09-07
PAK    Pakistan   205.71    881.91    302.14     Asia   No  1947-08-14
NGA     Nigeria   200.96    923.77    375.77   Africa   No  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63     Asia   No  1971-03-26
RUS       Rusia   146.79  17098.25   1530.75      NaN   No  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  America   Si  1810-09-16
JPN       Japon   126.22    377.97   4872.42     Asia   Si         NaN
DEU    Alemania    83.02    357.11   3693.20   Europe   Si         NaN
FRA     Francia    67.02    640.68   2582.49   Europe   Si  1789-07-14
GBR          UK    66.44    242.50   2631.23   Europe   Si         NaN
ITA      Italia    60.36    301.34   1943.84   Europe   Si         NaN
ARG   Argentina    44.94   2780.40    637.49  America   No  1816-07-09
DZA     Algeria    43.38   2381.74    167.56   Africa   No  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  America   Si  1867-07-01
AUS   Australia    25.47   7692.02   1408.68  Oceania   Si         NaN
CHL       Chile    19.68    756.10    317.60  America   Si  1818-09-18
KAZ  Kazakistan    18.53   2724.90    159.41     Asia   No  1991-12-16

## <font color='blue'>**Comprendiendo la API de Pandas IO**</font>
[Pandas IO Tools](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) es la API que le permite guardar el contenido de los objetos Series y DataFrame en objetos Python, archivos de varios tipos, o, incluso, en el portapapeles. También permite cargar datos desde estas mismas estructuras.

### __Escribir archivos__
Los objetos Series y DataFrame tienen métodos que permiten escribir datos y etiquetas en el portapapeles o en los archivos. Se nombran con el patrón `.to_<file-type>()`, donde `<file-type>` es el tipo del archivo de destino.

Ya vimos como hacerlo hacia archivos CSV y Excel con `.to_csv()` y `.to_excel()`, pero hay otros, incluidos:

* `.to_json()`
* `.to_html()`
* `.to_sql()`
* `.to_pickle()`

Todavía hay más tipos de archivos en los que puede escribir, por lo que esta lista no es exhaustiva.

### __Leer archivos__
Las funciones de Pandas para leer el contenido de los archivos se nombran usando el patrón `.read_<file-type>()`, donde `<file-type>` indica el tipo de archivo a leer. Ya ha visto las funciones `read_csv()` y `read_excel()` de Pandas. Aquí hay algunos otros:

* `.read_json()`
* `.read_html()`
* `.read_sql()`
* `.read_pickle()`

Estas funciones tienen un parámetro que especifica la ruta del archivo de destino. Puede ser cualquier cadena válida que represente la ruta, ya sea en una máquina local o en una URL. Otros objetos también son aceptables según el tipo de archivo.

## <font color='blue'>**Trabajar con diferentes tipos de archivos**</font>

Pandas ofrece una amplia gama de posibilidades para guardar sus datos en archivos y cargar datos desde archivos. En esta sección, obtendrá más información sobre cómo trabajar con archivos CSV y Excel. También verá cómo usar otros tipos de archivos, como JSON, páginas web, bases de datos y archivos pickle de Python.

### __Archivos CSV__
Ya aprendimos a leer y escribir archivos CSV. Ahora profundicemos un poco más en los detalles. Cuando usa `.to_csv()` para guardar su DataFrame, puede proporcionar un argumento para el parámetro `path_or_buf` para especificar la ruta, el nombre y la extensión del archivo de destino.

`path_or_buf` es el primer argumento que obtendrá `.to_csv()`. Puede ser cualquier cadena que represente una ruta de archivo válida que incluya el nombre del archivo y su extensión. Lo has visto en un ejemplo anterior. Sin embargo, si omite `path_or_buf`, `.to_csv()` no creará ningún archivo. En su lugar, devolverá la cadena correspondiente:

In [12]:
df = pd.DataFrame(data=data).T
s = df.to_csv()
print(s)

,PAIS,POB,AREA,PGB,CONT,OCDE,IND
CHN,China,1398.72,9596.96,12234.78,Asia,No,
IND,India,1351.16,3287.26,2575.67,Asia,No,1947-08-15
USA,US,329.74,9833.52,19485.39,America,Si,1776-07-04
IDN,Indonesia,268.07,1910.93,1015.54,Asia,No,1945-08-17
BRA,Brasil,210.32,8515.77,2055.51,America,No,1822-09-07
PAK,Pakistan,205.71,881.91,302.14,Asia,No,1947-08-14
NGA,Nigeria,200.96,923.77,375.77,Africa,No,1960-10-01
BGD,Bangladesh,167.09,147.57,245.63,Asia,No,1971-03-26
RUS,Rusia,146.79,17098.25,1530.75,,No,1992-06-12
MEX,Mexico,126.58,1964.38,1158.23,America,Si,1810-09-16
JPN,Japon,126.22,377.97,4872.42,Asia,Si,
DEU,Alemania,83.02,357.11,3693.2,Europe,Si,
FRA,Francia,67.02,640.68,2582.49,Europe,Si,1789-07-14
GBR,UK,66.44,242.5,2631.23,Europe,Si,
ITA,Italia,60.36,301.34,1943.84,Europe,Si,
ARG,Argentina,44.94,2780.4,637.49,America,No,1816-07-09
DZA,Algeria,43.38,2381.74,167.56,Africa,No,1962-07-05
CAN,Canada,37.59,9984.67,1647.12,America,Si,1867-07-01
AUS,Australia,25.47,7692.02,1408.68,Oceania,Si,
CHL,Chile,19.68,756.1,317.6,America,Si,1818-09-18
KAZ,Kazakistan,18.53,2724.9,159.41,Asia,No,1991-12-16

Ahora tiene la cadena $s$ en lugar de un archivo CSV. También tiene algunos valores faltantes en su objeto DataFrame. Por ejemplo, el continente de Rusia y los días de la independencia de varios países (China, Japón, etc.) no están disponibles. En ciencia de datos y aprendizaje automático, debe manejar los valores faltantes con cuidado. ¡Pandas sobresale aquí! De manera predeterminada, Pandas usa el valor de `NaN` para reemplazar los valores que faltan.

In [13]:
df.loc['RUS', 'CONT']

nan

Cuando guarde su DataFrame en un archivo CSV, las cadenas vacías (`''`) representarán los datos que faltan. Puede ver esto tanto en su archivo data.csv como en la cadena $s$. Si desea cambiar este comportamiento, utilice el parámetro opcional `na_rep`:

In [14]:
df.to_csv('new-data.csv', na_rep='(missing)')

Este código genera el archivo _new-data.csv_, donde los valores que faltan ya no son cadenas vacías. Puede expandir el bloque de código a continuación para ver cómo debería verse este archivo:

In [15]:
!cat new-data.csv

,PAIS,POB,AREA,PGB,CONT,OCDE,IND
CHN,China,1398.72,9596.96,12234.78,Asia,No,(missing)
IND,India,1351.16,3287.26,2575.67,Asia,No,1947-08-15
USA,US,329.74,9833.52,19485.39,America,Si,1776-07-04
IDN,Indonesia,268.07,1910.93,1015.54,Asia,No,1945-08-17
BRA,Brasil,210.32,8515.77,2055.51,America,No,1822-09-07
PAK,Pakistan,205.71,881.91,302.14,Asia,No,1947-08-14
NGA,Nigeria,200.96,923.77,375.77,Africa,No,1960-10-01
BGD,Bangladesh,167.09,147.57,245.63,Asia,No,1971-03-26
RUS,Rusia,146.79,17098.25,1530.75,(missing),No,1992-06-12
MEX,Mexico,126.58,1964.38,1158.23,America,Si,1810-09-16
JPN,Japon,126.22,377.97,4872.42,Asia,Si,(missing)
DEU,Alemania,83.02,357.11,3693.2,Europe,Si,(missing)
FRA,Francia,67.02,640.68,2582.49,Europe,Si,1789-07-14
GBR,UK,66.44,242.5,2631.23,Europe,Si,(missing)
ITA,Italia,60.36,301.34,1943.84,Europe,Si,(missing)
ARG,Argentina,44.94,2780.4,637.49,America,No,1816-07-09
DZA,Algeria,43.38,2381.74,167.56,Africa,No,1962-07-05
CAN,Canada,37.59,9984.67,1647.12,America,Si,1867-07-01
AUS,Australia,25.47,7692.02,1408.68,Oceania,Si,(missing)
CHL,Chile,19.68,756.1,317.6,America,Si,1818-09-18
KAZ,Kazakistan,18.53,2724.9,159.41,Asia,No,1991-12-16

Cuando Pandas lee archivos, considera la cadena vacía ('') y algunos otros como valores faltantes de forma predeterminada:
`['-1. # IND', '1. # QNAN', '1. # IND', '-1. # QNAN', '# N / AN / A', '# N / A ',' N / A ',' n / a ',' NA ',' <NA> ',' #NA ',' NULL ',' null ',' NaN ',' -NaN ',' nan ' , '-nan', '']`

Para controlar qué valores se analizan como valores perdidos (que se indican con `NaN`), se especifica una cadena en `na_values`. Si especifica una lista de cadenas, todos los valores en ella se consideran valores perdidos. Si especifica un número (un flotante, como 5.0 o un número entero como 5), los valores equivalentes correspondientes también implicarán un valor faltante (en este caso efectivamente `[5.0, 5]` se reconocen como `NaN`).

Para anular completamente los valores predeterminados que se reconocen como faltantes, especifique `keep_default_na = False`.

In [16]:
pd.read_csv('new-data.csv', index_col=0, na_values='(missing)')

           PAIS      POB      AREA       PGB     CONT OCDE         IND
CHN       China  1398.72   9596.96  12234.78     Asia   No         NaN
IND       India  1351.16   3287.26   2575.67     Asia   No  1947-08-15
USA          US   329.74   9833.52  19485.39  America   Si  1776-07-04
IDN   Indonesia   268.07   1910.93   1015.54     Asia   No  1945-08-17
BRA      Brasil   210.32   8515.77   2055.51  America   No  1822-09-07
PAK    Pakistan   205.71    881.91    302.14     Asia   No  1947-08-14
NGA     Nigeria   200.96    923.77    375.77   Africa   No  1960-10-01
BGD  Bangladesh   167.09    147.57    245.63     Asia   No  1971-03-26
RUS       Rusia   146.79  17098.25   1530.75      NaN   No  1992-06-12
MEX      Mexico   126.58   1964.38   1158.23  America   Si  1810-09-16
JPN       Japon   126.22    377.97   4872.42     Asia   Si         NaN
DEU    Alemania    83.02    357.11   3693.20   Europe   Si         NaN
FRA     Francia    67.02    640.68   2582.49   Europe   Si  1789-07-14
GBR          UK    66.44    242.50   2631.23   Europe   Si         NaN
ITA      Italia    60.36    301.34   1943.84   Europe   Si         NaN
ARG   Argentina    44.94   2780.40    637.49  America   No  1816-07-09
DZA     Algeria    43.38   2381.74    167.56   Africa   No  1962-07-05
CAN      Canada    37.59   9984.67   1647.12  America   Si  1867-07-01
AUS   Australia    25.47   7692.02   1408.68  Oceania   Si         NaN
CHL       Chile    19.68    756.10    317.60  America   Si  1818-09-18
KAZ  Kazakistan    18.53   2724.90    159.41     Asia   No  1991-12-16

Aquí, marcó la cadena '(missing)' como una nueva etiqueta de datos faltantes, y Pandas la reemplazó con `NaN` cuando leyó el archivo.

Cuando carga datos de un archivo, Pandas asigna los tipos de datos a los valores de cada columna de forma predeterminada. Puede verificar estos tipos con `.dtypes`:

In [17]:
df = pd.read_csv('data.csv', index_col=0)
df.dtypes

PAIS     object
POB     float64
AREA    float64
PGB     float64
CONT     object
OCDE     object
IND      object
dtype: object

Las columnas con strings y fechas ('PAIS', 'CONT', 'OCDE' e 'IND') tienen el tipo de  de datos `object`. Mientras tanto, las columnas numéricas contienen números de punto flotante de 64 bits (`float64`).

Puede usar el parámetro `dtype` para especificar los tipos de datos deseados y `parse_dates` para forzar el uso del tipo `datetimes`:

In [18]:
dtypes = {'POB': 'float32', 'AREA': 'float32', 'PGB': 'float32'}
df = pd.read_csv('data.csv', index_col=0, dtype=dtypes,
                 parse_dates=['IND'])
print(df.dtypes, '\n')
df['IND']

PAIS            object
POB            float32
AREA           float32
PGB            float32
CONT            object
OCDE            object
IND     datetime64[ns]
dtype: object

CHN          NaT
IND   1947-08-15
USA   1776-07-04
IDN   1945-08-17
BRA   1822-09-07
PAK   1947-08-14
NGA   1960-10-01
BGD   1971-03-26
RUS   1992-06-12
MEX   1810-09-16
JPN          NaT
DEU          NaT
FRA   1789-07-14
GBR          NaT
ITA          NaT
ARG   1816-07-09
DZA   1962-07-05
CAN   1867-07-01
AUS          NaT
CHL   1818-09-18
KAZ   1991-12-16
Name: IND, dtype: datetime64[ns]

Ahora, tiene números de punto flotante de 32 bits (`float32`) como se especifica con `dtype`. Estos difieren ligeramente de los números originales de 64 bits debido a su menor precisión. Los valores de la última columna se consideran fechas y tienen el tipo de datos `datetime64`. Es por eso que los valores de `NaN` en esta columna se reemplazan con `NaT`.

Ahora que tiene fechas reales, puede guardarlas en el formato que desee:

In [19]:
df = pd.read_csv('data.csv', index_col=0, parse_dates=['IND'])
df.to_csv('formatted-data.csv', date_format='%d %B %Y')

Aquí, ha especificado que el parámetro date_format sea `'%B %d, %Y'`. Veamos el archivo resultante:

In [20]:
!cat formatted-data.csv

,PAIS,POB,AREA,PGB,CONT,OCDE,IND
CHN,China,1398.72,9596.96,12234.78,Asia,No,
IND,India,1351.16,3287.26,2575.67,Asia,No,15 August 1947
USA,US,329.74,9833.52,19485.39,America,Si,04 July 1776
IDN,Indonesia,268.07,1910.93,1015.54,Asia,No,17 August 1945
BRA,Brasil,210.32,8515.77,2055.51,America,No,07 September 1822
PAK,Pakistan,205.71,881.91,302.14,Asia,No,14 August 1947
NGA,Nigeria,200.96,923.77,375.77,Africa,No,01 October 1960
BGD,Bangladesh,167.09,147.57,245.63,Asia,No,26 March 1971
RUS,Rusia,146.79,17098.25,1530.75,,No,12 June 1992
MEX,Mexico,126.58,1964.38,1158.23,America,Si,16 September 1810
JPN,Japon,126.22,377.97,4872.42,Asia,Si,
DEU,Alemania,83.02,357.11,3693.2,Europe,Si,
FRA,Francia,67.02,640.68,2582.49,Europe,Si,14 July 1789
GBR,UK,66.44,242.5,2631.23,Europe,Si,
ITA,Italia,60.36,301.34,1943.84,Europe,Si,
ARG,Argentina,44.94,2780.4,637.49,America,No,09 July 1816
DZA,Algeria,43.38,2381.74,167.56,Africa,No,05 July 1962
CAN,Canada,37.59,9984.67,1647.12,America,Si,01 July 1867
AUS,Australia,25.47,7692.02,1408.68,Oceania,Si,
CHL,Chile,19.68,756.1,317.6,America,Si,18 September 1818
KAZ,Kazakistan,18.53,2724.9,159.41,Asia,No,16 December 1991

El formato de las fechas es diferente ahora. El formato `'%d %B %Y'` significa que la fecha mostrará primero el día, luego el nombre completo del mes, y finalmente el año completo.

Hay varios otros parámetros opcionales que puede usar con `.to_csv()`:

* `sep` denota un separador de valores.
* `decimal` indica un separador decimal.
* `encoding` establece la codificación del archivo.
* `header` especifica si desea escribir etiquetas de columna en el archivo.

Así es como pasaría argumentos para `sep` y `header`:

In [21]:
s = df.to_csv(sep=';', header=False)
print(s)

CHN;China;1398.72;9596.96;12234.78;Asia;No;
IND;India;1351.16;3287.26;2575.67;Asia;No;1947-08-15
USA;US;329.74;9833.52;19485.39;America;Si;1776-07-04
IDN;Indonesia;268.07;1910.93;1015.54;Asia;No;1945-08-17
BRA;Brasil;210.32;8515.77;2055.51;America;No;1822-09-07
PAK;Pakistan;205.71;881.91;302.14;Asia;No;1947-08-14
NGA;Nigeria;200.96;923.77;375.77;Africa;No;1960-10-01
BGD;Bangladesh;167.09;147.57;245.63;Asia;No;1971-03-26
RUS;Rusia;146.79;17098.25;1530.75;;No;1992-06-12
MEX;Mexico;126.58;1964.38;1158.23;America;Si;1810-09-16
JPN;Japon;126.22;377.97;4872.42;Asia;Si;
DEU;Alemania;83.02;357.11;3693.2;Europe;Si;
FRA;Francia;67.02;640.68;2582.49;Europe;Si;1789-07-14
GBR;UK;66.44;242.5;2631.23;Europe;Si;
ITA;Italia;60.36;301.34;1943.84;Europe;Si;
ARG;Argentina;44.94;2780.4;637.49;America;No;1816-07-09
DZA;Algeria;43.38;2381.74;167.56;Africa;No;1962-07-05
CAN;Canada;37.59;9984.67;1647.12;America;Si;1867-07-01
AUS;Australia;25.47;7692.02;1408.68;Oceania;Si;
CHL;Chile;19.68;756.1;317.6;America;Si;1818-09-18
KAZ;Kazakistan;18.53;2724.9;159.41;Asia;No;1991-12-16

In [22]:
s = df.to_csv(sep='\t', header=False)
print(s)

CHN	China	1398.72	9596.96	12234.78	Asia	No
IND	India	1351.16	3287.26	2575.67	Asia	No	1947-08-15
USA	US	329.74	9833.52	19485.39	America	Si	1776-07-04
IDN	Indonesia	268.07	1910.93	1015.54	Asia	No	1945-08-17
BRA	Brasil	210.32	8515.77	2055.51	America	No	1822-09-07
PAK	Pakistan	205.71	881.91	302.14	Asia	No	1947-08-14
NGA	Nigeria	200.96	923.77	375.77	Africa	No	1960-10-01
BGD	Bangladesh	167.09	147.57	245.63	Asia	No	1971-03-26
RUS	Rusia	146.79	17098.25	1530.75		No	1992-06-12
MEX	Mexico	126.58	1964.38	1158.23	America	Si	1810-09-16
JPN	Japon	126.22	377.97	4872.42	Asia	Si
DEU	Alemania	83.02	357.11	3693.2	Europe	Si
FRA	Francia	67.02	640.68	2582.49	Europe	Si	1789-07-14
GBR	UK	66.44	242.5	2631.23	Europe	Si
ITA	Italia	60.36	301.34	1943.84	Europe	Si
ARG	Argentina	44.94	2780.4	637.49	America	No	1816-07-09
DZA	Algeria	43.38	2381.74	167.56	Africa	No	1962-07-05
CAN	Canada	37.59	9984.67	1647.12	America	Si	1867-07-01
AUS	Australia	25.47	7692.02	1408.68	Oceania	Si
CHL	Chile	19.68	756.1	317.6	America	Si	1818-09-18
KAZ	Kazakistan	18.53	2724.9	159.41	Asia	No	1991-12-16

### __Archivos de Excel__
Ya aprendimos a leer y escribir archivos de Excel con Pandas. Sin embargo, hay algunas opciones más que vale la pena considerar. Por un lado, cuando usa `.to_excel()`, puede especificar el nombre de la hoja de trabajo de destino con el parámetro opcional `sheet_name`:

In [23]:
df = pd.DataFrame(data=data).T
df.to_excel('data.xlsx', sheet_name='Países')

In [24]:
import os
os.getcwd()

'/content'

Se ha creado un archivo _data.xlsx_ con una hoja de trabajo llamada _'Países'_ la cual contiene nuestros datos. La cadena `'data.xlsx'` es el argumento del parámetro `excel_writer` que define el nombre del archivo de Excel o su ruta.

Los parámetros opcionales `startrow` y `startcol` tienen un valor predeterminado de 0 e indican la celda superior izquierda donde deben comenzar a escribirse los datos:

In [25]:
df.to_excel('data-shifted.xlsx',
            sheet_name='Países',
            startrow=2, startcol=4)

Aquí, especifica que la tabla debe comenzar en la tercera fila y la quinta columna. También utilizó la indexación basada en cero, por lo que la tercera fila se indica con 2 y la quinta columna con 4. Verifiquen el contenido.

In [26]:
df1 = pd.read_excel('data.xlsx', sheet_name=0, index_col=0,
                   parse_dates=['IND'])
df2 = pd.read_excel('data.xlsx', sheet_name='Países', index_col=0,
                   parse_dates=['IND'])
df1 == df2

     PAIS   POB  AREA   PGB   CONT  OCDE    IND
CHN  True  True  True  True   True  True  False
IND  True  True  True  True   True  True   True
USA  True  True  True  True   True  True   True
IDN  True  True  True  True   True  True   True
BRA  True  True  True  True   True  True   True
PAK  True  True  True  True   True  True   True
NGA  True  True  True  True   True  True   True
BGD  True  True  True  True   True  True   True
RUS  True  True  True  True  False  True   True
MEX  True  True  True  True   True  True   True
JPN  True  True  True  True   True  True  False
DEU  True  True  True  True   True  True  False
FRA  True  True  True  True   True  True   True
GBR  True  True  True  True   True  True  False
ITA  True  True  True  True   True  True  False
ARG  True  True  True  True   True  True   True
DZA  True  True  True  True   True  True   True
CAN  True  True  True  True   True  True   True
AUS  True  True  True  True   True  True  False
CHL  True  True  True  True   True  True   True
KAZ  True  True  True  True   True  True   True

Ambas declaraciones anteriores crean el mismo DataFrame porque los parámetros `sheet_name` tienen los mismos valores. En ambos casos, `sheet_name=0` y `sheet_name='Países'` se refieren a la misma hoja de cálculo. El argumento `parse_dates=['IND']` le dice a Pandas que intente considerar los valores en esta columna como fechas u horas.

Hay otros parámetros opcionales que puede usar con `.read_excel()` y .`to_excel()` para determinar el motor de Excel, la codificación, la forma de manejar valores perdidos e infinitos, el método para escribir nombres de columna y etiquetas de fila, etc.

### <font color='green'>Actividad 1</font>

Eres el analista de datos en una empresa de tecnología. Se te ha asignado procesar y analizar un conjunto de datos de empleados. El objetivo es limpiar estos datos, realizar algunas transformaciones y luego responder algunas preguntas específicas.

Crearemos un archivo CSV basado en un DataFrame:
```
import pandas as pd
import numpy as np

np.random.seed(42)

nombres = ["Ana", "Juan", "Marta", "Pedro", "Isabel", "Jorge", "Luisa", "Carlos", "Esther", "David"]
apellidos = ["García", "López", "Martínez", "Rodríguez", "González", "Fernández", "Ruiz", "Ramirez", "Morales", "Torres"]

# Generar fechas de ingreso
fechas_de_ingreso = pd.date_range(start="2015-01-01", end="2022-09-01", freq='M')

empleados = {
    'Nombre': [f"{np.random.choice(nombres)} {np.random.choice(apellidos)}" for _ in range(100)],
    'Edad': np.random.randint(20, 60, 100),
    'Salario ($)': np.random.randint(25000, 75000, 100),
    'Fecha de Ingreso': np.random.choice(fechas_de_ingreso, 100),
    'Puesto': np.random.choice(["Desarrollador", "Diseñador", "Gerente", "Analista"], 100)
}

df = pd.DataFrame(empleados)
df.to_csv("empleados.csv", index=False)
```

1. Carga el archivo CSV empleados.csv en un DataFrame usando pandas.
2. Verifica si hay valores faltantes en cualquier columna y decide cómo manejarlos.
3. Filtra los registros de los empleados que se unieron después del 1 de enero de 2020.
4. Encuentra el salario promedio de los empleados según su puesto.
5. Agrega una columna "Antigüedad" al DataFrame que muestre el número de años desde la fecha de ingreso del empleado hasta la fecha actual.
6. Guarda los registros de los empleados con más de 3 años de antigüedad en un nuevo archivo CSV llamado empleados_antiguos.csv.
7. Carga el archivo empleados_antiguos.csv y encuentra el empleado con el salario más alto entre aquellos que tienen más de 3 años de antigüedad.

In [34]:
import pandas as pd
import numpy as np

np.random.seed(42)

nombres = ["Ana", "Juan", "Marta", "Pedro", "Isabel", "Jorge", "Luisa", "Carlos", "Esther", "David"]
apellidos = ["García", "López", "Martínez", "Rodríguez", "González", "Fernández", "Ruiz", "Ramirez", "Morales", "Torres"]

# Generar fechas de ingreso
fechas_de_ingreso = pd.date_range(start="2015-01-01", end="2022-09-01", freq='ME')

empleados = {
    'Nombre': [f"{np.random.choice(nombres)} {np.random.choice(apellidos)}" for _ in range(100)],
    'Edad': np.random.randint(20, 60, 100),
    'Salario ($)': np.random.randint(25000, 75000, 100),
    'Fecha de Ingreso': np.random.choice(fechas_de_ingreso, 100),
    'Puesto': np.random.choice(["Desarrollador", "Diseñador", "Gerente", "Analista"], 100)
}

df = pd.DataFrame(empleados)
df.to_csv("empleados.csv", index=False)

In [35]:
"""
1.  Carga el archivo CSV empleados.csv en un DataFrame usando pandas.
"""
df = pd.read_csv("empleados.csv")
display(df)

              Nombre  Edad  Salario ($) Fecha de Ingreso         Puesto
0    Luisa Rodríguez    41        42453       2016-07-31      Diseñador
1    Carlos González    30        61212       2016-05-31  Desarrollador
2       Luisa Torres    35        68525       2020-03-31      Diseñador
3         Marta Ruiz    52        72202       2016-07-31  Desarrollador
4    Carlos González    28        57635       2022-08-31        Gerente
..               ...   ...          ...              ...            ...
95        Pedro Ruiz    54        53940       2021-02-28        Gerente
96     Carlos García    36        62233       2022-06-30        Gerente
97     Jorge Ramirez    47        42019       2017-10-31      Diseñador
98  Isabel Rodríguez    49        71185       2015-07-31        Gerente
99    Juan Fernández    48        43077       2020-08-31       Analista

[100 rows x 5 columns]

In [36]:
"""
2.  Verifica si hay valores faltantes en cualquier columna y decide cómo
    manejarlos.
"""
print("La cantidad de nulos en cada columna quedan expresados a continuacion:")
df.isna().sum()

La cantidad de nulos en cada columna quedan expresados a continuacion:

Nombre              0
Edad                0
Salario ($)         0
Fecha de Ingreso    0
Puesto              0
dtype: int64

In [40]:
"""
3.  Filtra los registros de los empleados que se unieron después del 1 de enero
    de 2020.
"""
df[df['Fecha de Ingreso']>='2020-01-01']

              Nombre  Edad  Salario ($) Fecha de Ingreso         Puesto
2       Luisa Torres    35        68525       2020-03-31      Diseñador
4    Carlos González    28        57635       2022-08-31        Gerente
7     Jorge González    48        28420       2022-06-30       Analista
8       Juan Ramirez    22        56216       2022-06-30  Desarrollador
9        Jorge López    39        25301       2020-02-29  Desarrollador
18       Esther Ruiz    52        51641       2022-05-31        Gerente
21     David Morales    37        48093       2020-01-31       Analista
22    David González    59        25569       2020-04-30       Analista
23    Juan Rodríguez    20        63210       2020-03-31      Diseñador
24     Luisa Ramirez    30        59663       2020-09-30  Desarrollador
26       Pedro López    44        70681       2020-07-31       Analista
27  Carlos Rodríguez    42        32455       2021-04-30       Analista
31       Juan Torres    26        60777       2022-02-28  Desarrollador
34     Luisa Morales    21        59177       2021-06-30        Gerente
35   Carlos González    20        70017       2022-08-31  Desarrollador
36     Juan González    31        25784       2020-09-30        Gerente
38    Esther Morales    56        65864       2020-02-29        Gerente
39       Ana Morales    51        65328       2020-09-30  Desarrollador
40     Luisa Morales    28        37533       2021-04-30      Diseñador
42    Carlos Ramirez    38        64974       2022-06-30  Desarrollador
43      Marta García    35        30801       2022-06-30      Diseñador
45      Marta García    39        74689       2022-01-31       Analista
50       Juan García    27        48355       2020-09-30        Gerente
57      Ana González    54        31655       2020-09-30       Analista
61        Marta Ruiz    37        50547       2021-08-31      Diseñador
63    Pedro González    54        38403       2022-08-31       Analista
65        Pedro Ruiz    55        38121       2022-07-31        Gerente
66   Marta Fernández    52        35966       2021-12-31      Diseñador
73    Esther Morales    26        67675       2020-01-31  Desarrollador
77   Esther González    31        27491       2020-07-31       Analista
78      Ana Martínez    41        52236       2020-05-31  Desarrollador
81  Esther Rodríguez    57        44508       2021-02-28  Desarrollador
90    Luisa González    47        40202       2022-03-31      Diseñador
91        Ana García    52        64734       2021-09-30  Desarrollador
92       Marta López    24        32079       2022-06-30        Gerente
95        Pedro Ruiz    54        53940       2021-02-28        Gerente
96     Carlos García    36        62233       2022-06-30        Gerente
99    Juan Fernández    48        43077       2020-08-31       Analista

In [41]:
"""
4.  Encuentra el salario promedio de los empleados según su puesto.
"""
df.groupby(by='Puesto')['Salario ($)'].mean()

Puesto
Analista         43431.600000
Desarrollador    56552.500000
Diseñador        45168.600000
Gerente          46955.807692
Name: Salario ($), dtype: float64

In [50]:
"""
5.  Agrega una columna "Antigüedad" al DataFrame que muestre el número de años
    desde la fecha de ingreso del empleado hasta la fecha actual.
"""
df['Antigüedad'] = df['Fecha de Ingreso'].map(
    lambda x: (pd.to_datetime('today') - pd.to_datetime(x)).days//365
)
display(df)

,Nombre,Edad,Salario ($),Fecha de Ingreso,Puesto,Antigüedad
0,Luisa Rodríguez,41,42453,2016-07-31,Diseñador,8
1,Carlos González,30,61212,2016-05-31,Desarrollador,8
2,Luisa Torres,35,68525,2020-03-31,Diseñador,4
3,Marta Ruiz,52,72202,2016-07-31,Desarrollador,8
4,Carlos González,28,57635,2022-08-31,Gerente,2
...,...,...,...,...,...,...
95,Pedro Ruiz,54,53940,2021-02-28,Gerente,3
96,Carlos García,36,62233,2022-06-30,Gerente,2
97,Jorge Ramirez,47,42019,2017-10-31,Diseñador,7
98,Isabel Rodríguez,49,71185,2015-07-31,Gerente,9
99,Juan Fernández,48,43077,2020-08-31,Analista,4

In [51]:
"""
6.  Guarda los registros de los empleados con más de 3 años de antigüedad en un
    nuevo archivo CSV llamado empleados_antiguos.csv.
"""
df[df['Antigüedad']>=3].to_csv('empleados_antiguos.csv')

In [61]:
"""
7.  Carga el archivo empleados_antiguos.csv y encuentra el empleado con el
    salario más alto entre aquellos que tienen más de 3 años de antigüedad.
"""
df2 = pd.read_csv('empleados_antiguos.csv', index_col=0)
display(df2)
print(
    f"El empleado con salario más alto entre aquellos que tienes más de 3 "
    f"años de antigüedad es\n"
    f"{df['Nombre'].iloc[df['Salario ($)'].idxmax()]}, con un salario de "
    f"{df['Salario ($)'].max()}."
)

,Nombre,Edad,Salario ($),Fecha de Ingreso,Puesto,Antigüedad
0,Luisa Rodríguez,41,42453,2016-07-31,Diseñador,8
1,Carlos González,30,61212,2016-05-31,Desarrollador,8
2,Luisa Torres,35,68525,2020-03-31,Diseñador,4
3,Marta Ruiz,52,72202,2016-07-31,Desarrollador,8
5,Pedro Ramirez,25,58828,2019-10-31,Desarrollador,5
...,...,...,...,...,...,...
94,Jorge Ruiz,23,64567,2017-02-28,Desarrollador,7
95,Pedro Ruiz,54,53940,2021-02-28,Gerente,3
97,Jorge Ramirez,47,42019,2017-10-31,Diseñador,7
98,Isabel Rodríguez,49,71185,2015-07-31,Gerente,9
99,Juan Fernández,48,43077,2020-08-31,Analista,4

El empleado con salario más alto entre aquellos que tienes más de 3 años de antigüedad es
David Fernández, con un salario de 74758.

<font color='green'>Fin Actividad 1</font>

<img src="https://drive.google.com/uc?export=view&id=1Igtn9UXg6NGeRWsqh4hefQUjV0hmzlBv" width="100" align="left" title="Runa-perth">
<br clear="left">

##<font color='red'>__Actividad Bonus__</font>

### <font color='green'>Actividad 2</font>

Usando los archivos de la actividad anterior, divide el DataFrame original de empleados en archivos separados basados en el puesto de trabajo, y guarda cada subconjunto en un archivo CSV (por ejemplo: desarrolladores.csv, diseñadores.csv, etc.).

In [65]:
for puesto in set(df['Puesto']):
    df[df['Puesto']==puesto].to_csv(puesto+'.csv')
    print(f"{puesto}.csv exportado correctamente.")

Analista.csv exportado correctamente.
Diseñador.csv exportado correctamente.
Desarrollador.csv exportado correctamente.
Gerente.csv exportado correctamente.

<font color='green'>Fin Actividad 2</font>

<img src="https://drive.google.com/uc?export=view&id=1Igtn9UXg6NGeRWsqh4hefQUjV0hmzlBv" width="50" align="left" title="Runa-perth">
<br clear="left">